### ISSUE TITLE
Better compatibility with non-44.1 kHz tracks

### ISSUE THREAD

**Issue by Vivelin** [MattEqualsCoder/MSUScripter#104]
Now, I assume either PyMusicLooper or msupcm++ (or both) implicitly convert tracks to 44.1 kHz. This is fine for the end result and previews, but when trying to find loop points manually for 48 kHz tracks, this is kind of a pain in the ass. 

Assuming this is indeed some issue internal to the dependencies that you can't work around with a parameter or flag of some kind, would it be possible to show a warning for non-44.1 kHz tracks and automatically convert any entered samples? Obviously, this might result in some inaccuracies which is why I'd argue for a warning message of some kind, even when you do automatically convert it.

**Comment by Vivelin** [comment]
Discussed in Discord, this is an issue with Audacity 3.3 and up actually implicitly converting to 44.1 kHz. A warning about this might be good, though. Maybe in the Trim End / Loop Start tooltips or something? Or just the readme, idk.

**Comment by MattEqualsCoder** [comment]
My current thought is to put a little thing in the top right after selecting a non-44100Hz file or if you add multiple files due to what Phiggle said: 
![image](https://github.com/MattEqualsCoder/MSUScripter/assets/63823784/a73cce04-bec5-4088-b9b3-c8e0bdf2a11d)
