### ISSUE TITLE
Not detecting PyMusicLooper

### ISSUE THREAD

**Issue by codemann8** [MattEqualsCoder/MSUScripter#11]
I've installed PyMusicLooper and can run it via `py -m pymusiclooper` on CLI but this program doesn't detect it

**Comment by MattEqualsCoder** [comment]
Are you able to run it standalone in the CLI via just typing in pymusiclooper? That's how the MSU Scripter currently executes it rather than executing it via a Python command.

**Comment by codemann8** [comment]
I've never heard of being able to execute python programs as you would like an exe. How do you make an installed python program do that?

**Comment by codemann8** [comment]
I installed it via their #2 option: `pip install pymusiclooper` and upon running `pip show pymusiclooper` it gives the dir where it supposedly installs it, but I see no exe files there, so I can't say adding that dir to the PATH variable would help any.

**Comment by MattEqualsCoder** [comment]
I'm not sure how exactly it's setup to do that. I just followed the pymusiclooper pipx installation instructions on the creator's GitHub and it just worked from what I recall.

I can also try to look into adding an option to specify an execution command to run it in the case where running it in a standalone form doesn't work. I just can't easily do that because python could be in different locations and not in the path environment variable.

**Comment by codemann8** [comment]
Could you not just execute it as `py -m pymusiclooper`?

**Comment by MattEqualsCoder** [comment]
> I installed it via their second install option: `pip install pymusiclooper` and upon running `pip show pymusiclooper` it gives the dir where it supposedly installs it, but I see no exe files there, so I can't say adding that dir to the PATH variable would help any.

Ah, maybe the difference is I installed via pipx as that's what was recommended by the creator.

As far as running it via py -m, that requires the python directory to be in the path environment variable, which isn't always the case. Perhaps I can try to do some sort of cascade where I try it one way, then fall back to the other way.

Unfortunately I'll be out of town this weekend, so I won't be able to look at this until next week at the earliest.

**Comment by codemann8** [comment]
Ok, I see now, your way also requires the Python/Scripts folder to be in the PATH variable, so really it's a special case either way

**Comment by MattEqualsCoder** [comment]
Well, being able to execute py/python anywhere in the CLI requires the python execution directory to be environment path. Usually this happens automatically, but I've had cases where I had to do it manually for whatever reason.

But yeah, I'll give this a look when I get the chance.

**Comment by MattEqualsCoder** [comment]
@codemann8 This should be fixed in the new release: https://github.com/MattEqualsCoder/MSUScripter/releases/tag/v1.1.1

Let me know if you still run into problems.
