### ISSUE TITLE
Crash on "Swap Track"

### ISSUE THREAD

**Issue by Alaszun** [MattEqualsCoder/MSUScripter#137]
[msu-scripter_20241006.log](https://github.com/user-attachments/files/17273842/msu-scripter_20241006.log)

I was trying to swap an alternate for the main track. I got a crash with the above log.

If it matters, it was the last alternate trying to swap to the current version of the track.

**Comment by MattEqualsCoder** [comment]
Hah. Swapping first with last worked, but swapping last with first broke. Should have a fix in shortly.
