### ISSUE TITLE
Error when trying to add midi files

### ISSUE THREAD

**Issue by Believe82** [MattEqualsCoder/MSUScripter#139]
![image](https://github.com/user-attachments/assets/cb9cdabf-0672-4115-954a-97b16e92a59e)

**Comment by MattEqualsCoder** [comment]
@Believe82 Unfortunately, this appears to be coming from msupcm++, so there's not much I can really do here. It actually appears that libsox, the library used by msupcm++, doesn't support midis either. I'm guessing the reasoning is that midis can sound very different based on the sound font on the OS, so they can sound different for each person.

While not ideal, I think the best option here would be to find a different audio file that isn't in midi format, find a converter to change the midi file into a wav file, or record the midi yourself using software into a wav file.

**Comment by Believe82** [comment]
Alright I will look for a convertor, thanks for the quick reply!
