### ISSUE TITLE
MSU track overview

### ISSUE THREAD

**Issue by Vivelin** [MattEqualsCoder/MSUScripter#52]
It'd be nice to have an overview of all the tracks in an MSU project.

I think most people have a separate Excel sheet where they plan it out, but I'm too lazy for that and I don't really have a specific theme in mind, so if I could have an overview in MSU Scripter itself, that'd be really useful for me. 

Just a list of all the tracks and which songs are selected for it, if any. Clicking on one track would then open the details pane for that track.

**Comment by MattEqualsCoder** [comment]
@Vivelin Think something like this would work? 
![image](https://github.com/MattEqualsCoder/MSUScripter/assets/63823784/b1c94dc6-22a5-4138-8f40-91c2851d498f)

**Comment by Vivelin** [comment]
Yeah, that's wonderful. I think some people's Excel sheets tend to have some basic stats on them (like tracks done/not done?) but this is already very useful for me.

**Comment by MattEqualsCoder** [comment]
Hm, so here's what I've got, @Vivelin 

I added a new flag for if a song is finished or not:
![image](https://github.com/MattEqualsCoder/MSUScripter/assets/63823784/c6b49df1-f8c1-4d1a-83cf-ed933ceb8877)
![image](https://github.com/MattEqualsCoder/MSUScripter/assets/63823784/80ff730a-4ab7-481a-a54d-73c1fa19c499)

Wasn't entirely sure the best place to put it on the individual song page, but I suppose that works. 🤔

**Comment by Vivelin** [comment]
Oh, my bad. I was referring to the "x out of y tracks" sort of stats. I imagine this could be nice, though, when people first want to set songs and then later fix the loop points or something.

**Comment by MattEqualsCoder** [comment]
No worries, I can probably add both to the bottom. 

"X out of Y tracks have files associated with them"
"A out of B songs are marked as completed"
